// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mockPackage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommunicationClient is the client API for Communication service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommunicationClient interface {
	Increment(ctx context.Context, opts ...grpc.CallOption) (Communication_IncrementClient, error)
}

type communicationClient struct {
	cc grpc.ClientConnInterface
}

func NewCommunicationClient(cc grpc.ClientConnInterface) CommunicationClient {
	return &communicationClient{cc}
}

func (c *communicationClient) Increment(ctx context.Context, opts ...grpc.CallOption) (Communication_IncrementClient, error) {
	stream, err := c.cc.NewStream(ctx, &Communication_ServiceDesc.Streams[0], "/mockPackage.Communication/increment", opts...)
	if err != nil {
		return nil, err
	}
	x := &communicationIncrementClient{stream}
	return x, nil
}

type Communication_IncrementClient interface {
	Send(*IncRequest) error
	CloseAndRecv() (*Reply, error)
	grpc.ClientStream
}

type communicationIncrementClient struct {
	grpc.ClientStream
}

func (x *communicationIncrementClient) Send(m *IncRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *communicationIncrementClient) CloseAndRecv() (*Reply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Reply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommunicationServer is the server API for Communication service.
// All implementations must embed UnimplementedCommunicationServer
// for forward compatibility
type CommunicationServer interface {
	Increment(Communication_IncrementServer) error
	mustEmbedUnimplementedCommunicationServer()
}

// UnimplementedCommunicationServer must be embedded to have forward compatible implementations.
type UnimplementedCommunicationServer struct {
}

func (UnimplementedCommunicationServer) Increment(Communication_IncrementServer) error {
	return status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedCommunicationServer) mustEmbedUnimplementedCommunicationServer() {}

// UnsafeCommunicationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommunicationServer will
// result in compilation errors.
type UnsafeCommunicationServer interface {
	mustEmbedUnimplementedCommunicationServer()
}

func RegisterCommunicationServer(s grpc.ServiceRegistrar, srv CommunicationServer) {
	s.RegisterService(&Communication_ServiceDesc, srv)
}

func _Communication_Increment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommunicationServer).Increment(&communicationIncrementServer{stream})
}

type Communication_IncrementServer interface {
	SendAndClose(*Reply) error
	Recv() (*IncRequest, error)
	grpc.ServerStream
}

type communicationIncrementServer struct {
	grpc.ServerStream
}

func (x *communicationIncrementServer) SendAndClose(m *Reply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *communicationIncrementServer) Recv() (*IncRequest, error) {
	m := new(IncRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Communication_ServiceDesc is the grpc.ServiceDesc for Communication service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Communication_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mockPackage.Communication",
	HandlerType: (*CommunicationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "increment",
			Handler:       _Communication_Increment_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "increment/inc.proto",
}
